/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "SDD - PHYSICAL AI & HUMANOID ROBOTICS TEXTBOOK",
  "tagline": "Learning Physical AI and Robotics",
  "favicon": "img/favicon.ico",
  "url": "https://physicalhumanoidaitextbook.vercel.app",
  "baseUrl": "/",
  "organizationName": "muhammadabrar",
  "projectName": "physical-ai-humanoid-robotics-textbook",
  "deploymentBranch": "gh-pages",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ur"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/ph-ai-logo.png",
    "navbar": {
      "title": "AI Humanaoids and Robotics Textbook",
      "hideOnScroll": true,
      "style": "dark",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/ph-ai-logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Textbook"
        },
        {
          "href": "https://github.com/muhammadabrar02",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "i18n": {
            "defaultLocale": "en",
            "locales": [
              "en",
              "ur"
            ],
            "localeConfigs": {
              "ur": {
                "label": "اردو",
                "direction": "rtl"
              }
            }
          },
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/introduction/intro"
            }
          ]
        },
        {
          "title": "Social Profiles",
          "items": [
            {
              "label": "LinkenIN",
              "href": "https://www.linkedin.com/in/muhammadabrar009/"
            },
            {
              "label": "(X)Twitter",
              "href": "https://x.com/mabrar009"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/muhammadabrar02"
            }
          ]
        }
      ],
      "copyright": "Copyright � 2025 Physical AI & Humanoid Robotics Textbook, Built by Muhammad Abrar."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#000000ff",
          "backgroundColor": "#ffffffff"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "#282c34",
          "color": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "attr-value"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "comment",
              "block-comment",
              "prolog",
              "doctype",
              "cdata",
              "shebang"
            ],
            "style": {
              "color": "#999999"
            }
          },
          {
            "types": [
              "property",
              "number",
              "function-name",
              "constant",
              "symbol",
              "deleted"
            ],
            "style": {
              "color": "#5a9bcf"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ff8b50"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "#fc929e"
            }
          },
          {
            "types": [
              "string"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "selector",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#D8DEE9"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#79b6f2"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url",
              "variable"
            ],
            "style": {
              "color": "#d7deea"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "atrule",
              "class-name"
            ],
            "style": {
              "color": "#FAC863"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "fontWeight": "400"
            }
          },
          {
            "types": [
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
